# spark-master/tasks/main.yml
---

- name: Install Spark packages (master)
  tags:
    - hadoop
    - spark
    - master
  package:
    name='{{item}}'
    state=present
  with_items:
    - spark-history-server # History server for Apache Spark
    - spark-master # Server for Spark master


- name: Start Spark master services
  tags:
    - hadoop
    - spark
    - master
  service:
    name="{{item}}"
    state=started
    enabled=yes
  with_items:
    - spark-master

