# slurm-worker/tasks/main.yml
---

- name: Load distribution-specific parameters
  include: 'init-{{ansible_os_family}}.yml'

- name: Install SLURM worker packages
  package:
    name={{item}}
    state=latest
  with_items: '{{slurmd_packages}}'
